### ISSUE TITLE
What's the framework of final report?

### ISSUE THREAD

**Issue by LoisGong** [yifanshi127/E-health-app#10]
Cover page with project abstract and details of the team 
Introduction
Background (what is muscle fatigue, its causes, symptoms, treatments? What are the consequences of muscle fatigue and its clinical needs?)
Problem statement (what technologies available and what are we going to adopt to deal with the identified problem) 
Introduction of sEMG and assessment model (median frequency)
Functions and features (what function we plan to realise)
Description of modules (what are the main modules in our project)
Data acquisition
Data processing and transmission
Data storage  
Solution 
Framework (Diagram) explain the overall picture of how every component works together.
Hardware: What are the devices we used? How we used (using a picture of a person wearing the device)
Software (Algorithms here! How the code works/procedure)
Arduino C++ (algorithm, with a diagram to describe the process)
Database SQL + Python (tables, keys and relationship)
Webpage HTML (visualization of the functions)
Quantitative results and discussion
Visualization of the data (frequency domain, time domain etc.)
Detail analyses on the result, which part of the result is good/bad, which indicates it, what are the references. (refer to the sensitivity value)
What problems we encountered and how we solved (if it’s about the programming, then use a screenshot and refer to the codes in appendix)
What are the limitations and advantages of the project?
Do we have any future plan?
develop a mobile app so that customers can use their smartphones to access the data, which is more convenient
Use mobile phones to collect and process data, by bluetooth
use wifi transfer data, much fast?
Conclusion 
Reference 
Appendix 
c++ code
SQL code
HTML code

**Comment by syuingyang** [comment]
Refering to the USYD engineering report guideline: http://iwrite.sydney.edu.au/ENGINEERING/Reports/Design-Reports/Writing-Engineering-Design-Reports.html

**Comment by ZhanpengTang** [comment]
Can we add meeting minutes?

**Comment by ZhanpengTang** [comment]
we don't use SQL code, but use python
