### ISSUE TITLE
s-EMG frequency

### ISSUE THREAD

**Issue by BrownXu** [yifanshi127/E-health-app#2]
As we need to collect s-EMG under 300HZ, so we need a sampling rate at 600HZ, so I need to collect data every 1.6ms, but we don't know how fast the Ardunio can execute the codes, so we can't get an accurate frequency.

**Comment by syuingyang** [comment]
research will be done on the Arduino speed

**Comment by ZhanpengTang** [comment]
The frequency of an EMG signal is between 0 to 500 Hz. However, the usable energy of EMG signal is dominant between 50-150 Hz. Does it means we can use as low as 50 Hz?

**Comment by ZhanpengTang** [comment]
read EMG sensor every 2 ms
