### ISSUE TITLE
MySignals_HW_profile_BLE_V001 official documents has wrong UUID value

### ISSUE THREAD

**Issue by BrownXu** [yifanshi127/E-health-app#4]

**Comment by BrownXu** [comment]
[MySignals_HW_profile_BLE_V001.pdf](https://github.com/yifanshi127/E-health-app/files/3717521/MySignals_HW_profile_BLE_V001.pdf)
I have fixed a bug and now able to get a stable Bluetooth connection with that board. But I found the UUID value in the documents is not correct, so I can't get the right data. Our tutor told me maybe our device version didn't match the document's version.

**Comment by LoisGong** [comment]
> [MySignals_HW_profile_BLE_V001.pdf](https://github.com/yifanshi127/E-health-app/files/3717521/MySignals_HW_profile_BLE_V001.pdf)
> I have fixed a bug and now able to get a stable Bluetooth connection with that board. But I found the UUID value in the documents is not correct, so I can't get the right data. Our tutor told me maybe our device version didn't match the document's version.

Good!

**Comment by ZhanpengTang** [comment]
What about try all UUID in the document?

**Comment by ZhanpengTang** [comment]
Use handle number instead the handle name can fix this problem
