### ISSUE TITLE
Realtime visualisation of line graph

### ISSUE THREAD

**Issue by arifhussain007** [yifanshi127/E-health-app#7]
How to visualise real-time data in Django. Already implemented using html and javascript. But need to integrate into Django framework. Maybe append some files into it.

**Comment by LoisGong** [comment]
We could ask the tutors next week concerning visualisation.

**Comment by ZhanpengTang** [comment]
What about use Chart.js?
https://www.chartjs.org

**Comment by ZhanpengTang** [comment]
now we can display it in the smartphone end now. we use python finally.

**Comment by ZhanpengTang** [comment]
Show the real-time data on the smartphone instand of the website.
This function can be implemented by Numpy, Matpolt(python).
