### ISSUE TITLE
Dynamic graphs on web pages

### ISSUE THREAD

**Issue by ZhanpengTang** [yifanshi127/E-health-app#9]
Unable to output dynamic graphs on web pages via Django
Anyone can help?

**Comment by LoisGong** [comment]
Try to google it, if can't find anything, we'll ask the tutor.

**Comment by arifhussain007** [comment]
i am trying to resolve this issue.

**Comment by ZhanpengTang** [comment]
Try AJAX.
https://code.djangoproject.com/wiki/AJAX
https://simpleisbetterthancomplex.com/tutorial/2016/08/29/how-to-work-with-ajax-request-with-django.html
